name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install and Build Backend
        run: |
          cd backend
          npm ci
          npm run build

      - name: Install and Build Frontend
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Run Backend Tests
        run: |
          cd backend
          npm test
